package com.uptourism.pms.health;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * Minimal entity used to verify JPA and database connectivity.
 */
@Entity
@Table(name = "health_checks")
public class HealthCheckEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String status;

    @Column(name = "checked_at", nullable = false, updatable = false)
    private Instant checkedAt = Instant.now();

    public HealthCheckEntity() {
    }

    public HealthCheckEntity(String status) {
        this.status = status;
    }

    // PUBLIC_INTERFACE
    public Long getId() {
        /** Returns the autogenerated ID of the health check row. */
        return id;
    }

    // PUBLIC_INTERFACE
    public String getStatus() {
        /** Returns the status message saved for the health check row. */
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // PUBLIC_INTERFACE
    public Instant getCheckedAt() {
        /** Returns the timestamp when this health row was created. */
        return checkedAt;
    }
}
